remote_theme: pmarsceill/just-the-docs # https://github.com/pmarsceill/just-the-docs
color_scheme: custom

title: Billzonian
baseurl: "/Billzonian"
url: "https://seriousguy888.github.io"

permalink: /:categories/:year-:month-:day/:title

last_edit_timestamp: true
last_edit_time_format: "%Y-%m-%d"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/SeriousGuy888/Billzonian"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "tree"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      image: "/images/logo/logo.png"