remote_theme: pmarsceill/just-the-docs # https://github.com/pmarsceill/just-the-docs
color_scheme: custom

title: Billzonian
baseurl: "/Billzonian"
url: "https://seriousguy888.github.io"

last_edit_timestamp: true
last_edit_time_format: "%Y-%m-%d"